swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /todos:
    get:
      tags:
      - developers
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      produces:
      - application/json
      parameters:
      - in: query
        name: all
        description: returning all elements
        required: false
        type: string
      responses:
        200:
          description: list all results
          schema:
            type: array
            items:
              $ref: '#/definitions/TodoItem'
        400:
          description: bad input parameter
    post:
      tags:
      - admins
      summary: updates todo list with new state
      operationId: updateTodos
      description: Updates the todo list with client new state
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: inventoryItem
        description: Inventory item to add
        schema:
          $ref: '#/definitions/TodoItem'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
definitions:
  TodoItem:
    type: object
    required:
    - id
    - text
    properties:
      id:
        type: integer
        format: uuid
        example: 1
      text:
        type: string
        example: Learn react
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /manuelgqm5/todoApp/1.0.0
schemes:
 - https
